[versions]
agp-version = "8.9.0"
core-version = "1.10.1"
appcompat-version = "1.6.1"
kotlin-version = "2.1.0"
material-version = "1.10.0"

constraint-version = "2.2.1"
navigation-fragment-version = "2.6.0"
navigation-version = "2.6.0"
lifecycle-version = "2.2.0"
room-version = "2.6.1"
junit-version = "4.13.2"
ext-junit-version = "1.1.5"
espresso-version = "3.5.1"
okhttp-version = "4.12.0"
retrofit-version = "2.11.0"
banner-version = "2.1.0"
swiperefresh-version = "1.1.0"
immersionbar-version = "3.0.0"
agentweb-version = "4.1.4"
yutilskt-version = "3.4.0"
brvha-version = "3.0.6"
glide-version = "4.16.0"
flow-layout-version = "1.1.2"
vertical-version = "1.2.9"

task-tree = "2.1.1"
devtools-ksp = "2.0.21-1.0.27"

[libraries]
# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-version" }

# AndroidX Core
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-version" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat-version" }
material = { group = "com.google.android.material", name = "material", version.ref = "material-version" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint-version" }

# Navigation
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation-fragment-version" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation-version" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-version" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-version" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-version" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit-version" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-version" }

# Network
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp-version" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp-version" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-version" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit-version" }

# UI Components
banner = { group = "com.youth.banner", name = "banner", version.ref = "banner-version" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh-version" }
immersionbar = { group = "com.gyf.immersionbar", name = "immersionbar", version.ref = "immersionbar-version" }
agentweb = { group = "com.just.agentweb", name = "agentweb-androidx", version.ref = "agentweb-version" }
yutilskt = { group = "com.github.yechaoa.YUtils", name = "yutilskt", version.ref = "yutilskt-version" }
brvha = { group = "com.github.CymChad", name = "BaseRecyclerViewAdapterHelper", version.ref = "brvha-version" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide-version" }
flowlayout = { group = "com.hyman", name = "flowlayout-lib", version.ref = "flow-layout-version" }
vertical-tablayout = { group = "q.rorbin", name = "VerticalTabLayout", version.ref = "vertical-version" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp-version" }
android-library = { id = "com.android.library", version.ref = "agp-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
task-tree = { id = "com.dorongold.task-tree", version.ref = "task-tree" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }



